import ex2.ex2Sol as ex2Sol
from ex2.HMMBigramClass import HMMBigramTagger as hmm

pseudo = {'Ridiculous': 'JJ', 'Film': 'NN-HL', "Askington's": 'NP$', 'inexpressible': 'JJ', 'mad': 'NNS',
          'purtiest': 'JJT', 'aqueducts': 'NNS', 'trip-hammer': 'NN', 'sobbed': 'VBN', 'overloud': 'JJ',
          'modifiers': 'NNS', 'theatres': 'NNS', 'sherbet-colored': 'JJ', 'forbore': 'VBD', 'Content': 'JJ',
          'dealerships': 'NNS', 'filched': 'VBD', 'Momoyama': 'NP', 'Catatonia': 'NP', 'out-dated': 'JJ',
          '4000-plus': 'CD', 'welts': 'NNS', "nibs'": 'NN$', 'tigress': 'NN', 'whichever-the-hell': 'WDT',
          'mammas': 'NNS', 'parboiled': 'VBD', 'claret': 'JJ', 'cremate': 'VB', 'Quint': 'NP', 'Perelman': 'NP',
          'Gisele': 'NP', 'pre-empting': 'JJ', 'Cabrini': 'NP', 'drowsily': 'RB', "flower's": 'NN$', 'Kanto': 'NP',
          'patriarchy': 'NN', 'Peony': 'NP', 'fray': 'NN', 'biter': 'NN', 'boxcar': 'NN', "squatter's": 'NN$',
          'By-the-Sea': 'NP', "Roylott's": 'NP$', 'one-two-three': 'NN', 'figuring': 'NN', "Best's": 'NP$',
          'funny': 'JJ-NC', 'rumpus': 'NN', 'Phineoppus': 'NP', 'Jungian': 'JJ', 'perched': 'VBD', 'desecration': 'NN',
          'pacifies': 'VBZ', 'Minute': 'NN-TL', 'courtyards': 'NNS', 'somersaults': 'NNS', 'hiking': 'VBG',
          'portfolio': 'NN', 'wrought': 'VBD', "Lalaurie's": 'NP$', 'lath': 'NN', 'five-hundred-dollar': 'JJ',
          'singsonged': 'VBD', 'Married': 'VBN', 'stung': 'VBN', 'chemistries': 'NNS', 'olive-flushed': 'JJ',
          'Evadna': 'NP', 'agricolas': 'FW-NNS', 'absolution': 'NN', 'anxieties': 'NNS', 'Zingggg-O': 'UH',
          'non-English': 'NN', 'Miro': 'NP', 'adjudged': 'VBN', 'careerism': 'NN', 'wealthiest': 'JJT',
          "d'art": 'FW-IN+NN', 'reunions': 'NNS', 'Out': 'RB', 'Graves': 'NP', 'steely': 'JJ', 'Jennifer': 'NP',
          'amulet': 'NN', 'Answer': 'VB', 'argot': 'NN', 'ad-lib': 'NN', 'knee-length': 'JJ', 'vaginal': 'NN',
          "Johnnie's": 'NP$', 'gagwriters': 'NNS', 'cockroaches': 'NNS', 'cubist': 'NN', 'too-expensive': 'JJ',
          'sycophants': 'NNS', 'doweling': 'VBG', 'NRA': 'NP-TL', 'screeches': 'NNS', "Cezanne's": 'NP$',
          'hanged': 'VBD', 'visrhanik': 'NN-NC', "Elec's": 'NP$', 'aquam': 'FW-NN', 'housepaint': 'NN',
          'flageolet': 'NN', 'fawn-colored': 'JJ', 'grating': 'NN', "Francie's": 'NP$', "what's-his-name": 'NN',
          'nary': 'ABN', 'steels': 'NNS', 'gratingly': 'RB', 'switchblade': 'NN', 'Smug': 'JJ', 'tweedy': 'JJ',
          'Anthea': 'NP', 'forepart': 'NN', 'Modigliani': 'NP', 'Swallow': 'NN-TL', 'Bini': 'NP', 'Presidential': 'JJ',
          'uptown': 'RB', 'Ab63711-r': 'NP', 'Petite': 'JJ', 'Bambi': 'NP', 'buttocks': 'NNS', 'overcooked': 'VBN',
          'dragon': 'NN', 'Thankful': 'JJ', "cook's": 'NN$', 'Calf': 'NN-TL', 'Seashore': 'NN', 'likee': 'VB',
          'oatmeal': 'NN', "Kitty's": 'NP+BEZ', 'lowly': 'JJ', 'flippant': 'JJ', 'neatest': 'JJT', 'Scandal': 'NN-TL',
          'hotbed': 'NN', 'Caneli': 'NP', 'morning-frightened': 'JJ', 'Dingy-looking': 'JJ', 'diapiace': 'FW-VBZ',
          "Thoreau's": 'NP$', 'Longue': 'NP', 'wager': 'VB', "Tommy's": 'NP$', 'Momma': 'NP', 'hors': 'FW-RB',
          'Suzanne': 'NP', 'Brighetti': 'NP', 'flop': 'NN', 'patronized': 'VBD', 'shifty': 'JJ', 'Inscribed': 'VBN',
          'turnaround': 'NN', 'wieners': 'NNS', 'Kare': 'NN-TL', 'type': 'VB', 'rattling': 'NN',
          "helsq'iyokom": 'FW-NN', 'unfalteringly': 'RB', 'Tredding': 'NP', 'excuses': 'NNS', 'Cowbird': 'NN',
          'lugged': 'VBN', 'straddled': 'VBD', 'pratakku': 'FW-NN', 'hooch': 'NN', 'semi-ambiguous': 'JJ',
          'helluva': 'JJ', 'cold-bloodedly': 'RB', 'typed': 'VBD', 'Geology': 'NN', 'non-writers': 'NNS',
          'femme': 'FW-NN', "drummer's": 'NN$', 'sarcastic': 'JJ', 'clattery': 'JJ', 'all-American-boy': 'JJ',
          'Sonny': 'NP', 'Vivaldi': 'NP', 'Elsewhere': 'NN', 'sandalwood': 'NN', 'quaking': 'VBG', 'pact': 'NN',
          'Chinaman': 'NP', 'hefty': 'JJ', "Captain's": 'NN$-TL', 'grandly': 'RB', "Feathertop's": 'NP$',
          'girlie': 'NN', 'suburbia': 'NN', 'Delhi': 'NP', 'showering': 'VBG', 'fluff': 'NN', 'effloresce': 'VB',
          'sun-suit': 'NN', 'it-wit': 'NN', 'opalescent': 'JJ', 'Karamazov': 'NP-TL', 'prank': 'NN', 'whitens': 'VBZ',
          'Deus': 'FW-NP', 'not-so-pale': 'JJ', "Via's": 'NP$', 'F-major': 'NP-TL', 'Torino': 'NP',
          "Quasimodo's": 'NP$', 'portly': 'JJ', 'Broiled': 'VBN', 'rotundity': 'NN', 'his': 'PP$-TL',
          "cousins'": 'NNS$', 'reeked': 'VBD', 'Mushr': 'NP', 'Crosbys': 'NPS', 'yanking': 'VBG', 'snoop': 'VB',
          'contentment': 'NN', 'Camels': 'NNS', 'wand': 'NN', 'Thalbergs': 'NPS', "slave's": 'NN$', 'Dilys': 'NP',
          'russe': 'NN', 'Brainards': 'NPS', 'instigating': 'VBG', 'Ambiguity': 'NN', 'Fella': 'NN', 'unhinged': 'VBN',
          'Ready': 'JJ', 'Chalmers': 'NPS', 'flyaway': 'JJ', 'spats': 'NNS', 'snippy': 'JJ', "bedroom's": 'NN$',
          'manic-depressive': 'JJ', 'Fing': 'NP', 'Sistine': 'JJ-TL', 'Instantaneously': 'RB', 'Arch': 'NN-TL',
          'indigestion': 'NN', 'chump': 'NN', 'clonic': 'JJ', 'roasted': 'VBD', 'poshest': 'JJT', 'Gasse': 'NN-TL',
          'photorealism': 'NN', 'mumbling': 'VBG', 'mistrusted': 'VBD', 'vertebrae': 'NNS', 'mingling': 'VBG',
          'Ardmore': 'NP', 'insulting': 'VBG', 'bubbly': 'JJ', 'Wilhelmina': 'NP', 'foal': 'NN', 'atonally': 'RB',
          'Kobayashi': 'NP', "Bobbie's": 'NP$', 'Indefinite': 'JJ', 'Strike': 'VB', "Delphine's": 'NP$', 'Belle': 'NP',
          'punches': 'NNS', 'MacIsaacs': 'NP-TL', 'unruly': 'JJ', 'del': 'FW-IN+AT-TL', 'davenport': 'NN',
          'chassis': 'NN', 'ale': 'NN', 'unflagging': 'JJ', 'time': 'VB', 'Dharma': 'NP-TL', 'Forebearing': 'VBG',
          'draining': 'VBG', 'Monmouth': 'NP', 'Mind': 'VB', 'red-haired': 'JJ', 'home-blend': 'NN', 'Dearly': 'RB',
          "She'arim": 'NP', 'drowsing': 'VBG', 'persona': 'FW-NN', 'jimmied': 'VBD', 'Tjokorda': 'NP',
          'pityingly': 'RB', 'Slug': 'VB', 'ravenous': 'JJ', 'bathrooms': 'NNS', 'straightaway': 'RB', 'PWA': 'NP-TL',
          'traitor': 'NN', 'infected': 'VBD', 'fishing-boat': 'NN', 'honey-in-the-sun': 'JJ', 'Fairbrothers': 'NPS',
          'noisier': 'JJR', 'trustingly': 'RB', 'daydreaming': 'NN', 'commissary': 'NN', 'flautist': 'NN',
          'scapegoat': 'NN', 'Trianon': 'NP-TL', 'unco-operative': 'JJ', 'middles': 'NNS', 'mist-like': 'JJ',
          'bothersome': 'JJ', 'P.GA': 'NP', 'derivations': 'NNS', 'fumed': 'VBD', 'vent': 'VB', 'Fox': 'NN-TL',
          'Yiddish': 'NP', 'Attending': 'VBG', 'brazier': 'NN', "wieners'": 'NNS$', 'PTA': 'NP-TL', 'mockery': 'NN',
          'Rathbones': 'NPS', 'freakish': 'JJ', 'Burkette': 'NP', 'carousing': 'VBG', 'flashback': 'NN',
          "Bancroft's": 'NP$', 'shackled': 'VBN', 'gags': 'NNS', "Kirby's": 'NP$', "Concetta's": 'NP$',
          "Hadn't": 'HVD*', 'baby-sitter': 'NN', 'Eddyman': 'NP', 'Mormon': 'NP-TL', 'kibbutzim': 'NNS',
          'cameos': 'NNS', 'outcry': 'NN', 'raving': 'VBG', 'plumb': 'NN', 'cigars': 'NNS', 'Foreigners': 'NNS',
          'cacophony': 'NN', 'Backyard': 'NN-TL', 'Joviality': 'NN', 'squirted': 'VBD', 'fold': 'VB', "Romeo's": 'NP$',
          'Gompachi': 'NP', 'Balinese': 'NP', 'Groggins': 'NP', 'meteoric': 'JJ', "Shafer's": 'NP$', 'nigs': 'NNS',
          'snapshots': 'NNS', 'Houdini': 'NP', 'Craddock': 'NP', 'Marvelous': 'JJ', "Fink's": 'NP$', 'balanced': 'VBD',
          'Alberto': 'NP', 'bit': 'VBN', 'Sssshoo': 'UH', "freight's": 'NN$', 'Replies': 'NNS', 'jeunes': 'FW-JJ',
          "Buzz's": 'NP$', 'Bananas': 'NNS', 'Kodaks': 'NPS', 'warty': 'JJ', 'frenziedly': 'RB', 'Name': 'VB',
          'Move': 'VB', 'round-eyed': 'JJ', 'ocarina': 'NN', 'M-m-m': 'UH', 'Reichstag': 'NP', 'midwife': 'NN',
          'motioning': 'VBG', 'sake': 'UH', 'scrumptious': 'JJ', 'mater': 'FW-NN', 'haircuts': 'NNS', 'Yuki': 'NP',
          'exasperate': 'VB', 'Conduit': 'NN-TL', 'Skolkau': 'NP-TL', "6'": 'NN', 'misdirectors': 'NNS',
          'chapel-like': 'JJ', "J'ai": 'FW-PPSS+HV', 'Becoming': 'VBG', "sparrow's": 'NN$', 'Leather': 'NN-TL',
          'clincher': 'NN', 'Christmastime': 'NP', 'Kansas-Nebraska': 'NP-TL', 'lettering': 'VBG', 'hot-slough': 'JJ',
          'plain-out': 'RB', 'Taylors': 'NPS', 'pointless': 'JJ', 'daffodils': 'NNS', 'sap': 'NN', 'drab-haired': 'JJ',
          'pivoting': 'VBG', 'ransacking': 'VBG', 'leitmotiv': 'NN', 'Tolley': 'NP', 'frenzy-free': 'JJ',
          'cobblestones': 'NNS', 'Fairview': 'NP', 'relict': 'NN', 'Dancing': 'VBG-TL', 'buffeted': 'VBN',
          'odds-on': 'JJ', 'vignette': 'NN', 'SalFininistas': 'NP-HL', 'ologies': 'NNS', 'willowy': 'JJ',
          'livers': 'NNS', 'repetitive': 'JJ', 'anatomicals': 'NNS', 'outfielders': 'NNS', 'harm': 'VB',
          'Francoisette': 'NP', 'Glendale': 'NP', 'fishmongers': 'NNS', "Roy's": 'NP$', 'Gauntley': 'NP',
          'ruining': 'VBG', 'Quasimodo': 'NP', 'Cal-Neva': 'NP', 'fishpond': 'NN', "Mare's": 'NN$-TL',
          'nice-looking': 'JJ', 'astringency': 'NN', 'reliably': 'RB', 'Fauntleroy': 'NP-TL', 'Unimpressed': 'JJ',
          'spellbound': 'VBN', 'punishing': 'VBG', 'stumpy': 'JJ', 'lodges': 'NNS', 'snow-fence': 'NN',
          "Spencer's": 'NP$', 'parkish': 'JJ', 'enfant': 'FW-NN', 'Financing': 'VBG', "Opera's": 'NN$-TL',
          'parquet': 'NN', 'Angst': 'FW-NN', 'Webber': 'NP', 'Whosoever': 'WPS', 'schnooks': 'NNS', 'gagline': 'NN',
          'Askington': 'NP', 'rivals': 'NNS', 'splayed': 'VBD', 'beckoned': 'VBN', 'iniquitous': 'JJ',
          'pocketful': 'NN', 'delicately': 'RB', 'stardom': 'NN', 'fascinatingly': 'RB', 'fly-boy': 'NN', "bar'l": 'NN',
          'charlotte': 'NN', 'furiouser': 'JJR', "policeman's": 'NN$', 'pickins': 'NNS', 'Salamander': 'NN-TL',
          'Rosa': 'NP', 'ellipsis': 'NN', 'Bolshevistic': 'JJ', "Lalauries'": 'NPS$', 'Furiouser': 'JJR',
          'grammarians': 'NNS', 'Rakestraw': 'NP', "rockin'": 'JJ', 'Crumb': 'NP', 'waistcoat': 'NN', 'Cal': 'NP',
          'feathery': 'JJ', 'wildness': 'NN', 'Boats': 'NP', 'Sudanese': 'JJ', 'Vindication': 'NN', 'sorted': 'VBD',
          'aqua-lung': 'NN', 'Methuselah': 'NP', 'Goolick': 'UH', 'forked': 'VBN', 'commiserate': 'VB',
          'tangled': 'VBD', 'Eats': 'NNS-TL', 'Shafer': 'NP', 'paraphrase': 'NN', "Arlene's": 'NP+BEZ', 'Hair': 'NN',
          'fast-frozen': 'JJ', "ever-lovin'": 'JJ', 'unpaintable': 'JJ', 'A-Z': 'NP-TL', 'coursing': 'VBG',
          'tangos': 'NNS', 'finger-held': 'JJ', 'gasser': 'NN', 'rusted': 'VBN', 'Abruptly': 'RB', 'revulsion': 'NN-HL',
          'Allstates-Zenith': 'NP', 'amphibology': 'NN', 'Ceecee': 'NP', 'shrub-covered': 'JJ', 'holystones': 'NNS',
          'wire-haired': 'JJ', 'Crombie': 'NP', 'Lake': 'NP-HL', 'screw-loose': 'JJ', 'gird': 'VB', 'yore': 'NN',
          'incredulity': 'NN', 'bookish': 'JJ', 'Puny': 'JJ', 'poked': 'VBN', 'shocking': 'VBG', 'overexcited': 'VBN',
          'McKenzie': 'NP', 'raindrops': 'NNS', 'Mattie': 'NP', "egotist's": 'NN$', 'snobbishly': 'RB', 'giblet': 'NN',
          'much-needed': 'JJ', 'hoof-and-mouth': 'NN', 'misses': 'NNS', "Kroger's": 'NP$', 'cannonball': 'NN',
          'nettled': 'VBN', 'Drive': 'VB', 'thin-soled': 'JJ', 'clutch': 'VB', 'Krishna': 'NP', 'soulfully': 'RB',
          'prudent': 'JJ', 'Marquess': 'NN-TL', 'yelled': 'VBN', 'Gables': 'NPS', 'insolently': 'RB', 'Pompeii': 'NP',
          'purposeless': 'JJ', 'Toonker': 'NP', 'Bugatti': 'NP', 'redheaded': 'JJ', 'ajar': 'RB', 'Volare': 'NP',
          'fret': 'VB', 'gardening': 'VBG', 'Spa': 'NN-TL', 'refolded': 'VBD', 'uncomfortably': 'RB', 'Signore': 'NP',
          'tactful': 'JJ', 'time-cast': 'JJ', "roulette's": 'NN+BEZ', 'wonderfully': 'RB', 'Lust': 'NN-TL',
          'Cady': 'NP', 'yelping': 'VBG', 'acknowledgments': 'NNS', "Edythe's": 'NP$', 'Allegheny': 'NP-TL',
          'meted': 'VBD', 'tallow': 'NN', 'bloodspots': 'NNS', 'shriek': 'VB', 'big-town': 'NN', 'Sewickley': 'NP',
          'boy': 'UH', 'cosy': 'JJ', 'Alokut': 'NP', 'cancels': 'VBZ', 'indecisively': 'RB', 'pigeonhole': 'NN',
          'Quietly': 'RB', 'Khartoum': 'NP', 'affronted': 'VBN', 'eludes': 'VBZ', 'chaulmoogra': 'NN',
          'nine-to-five': 'JJ', 'eloped': 'VBD', 'di': 'FW-IN-TL', 'unnaturally': 'RB', "C'un": 'NN-TL',
          'headstones': 'NNS', 'effete': 'JJ', 'ninety-six': 'CD', 'barbarian': 'NN', 'satin-covered': 'JJ',
          'Wolf': 'NN-TL', 'Bifutek-san': 'NP', 'besmirched': 'VBD', 'warmish': 'JJ', 'Artfully': 'RB',
          'Calloused': 'VBN', 'Dogs': 'NNS-TL', 'masterly': 'JJ', "rat's": 'NN$', 'porches': 'NNS', 'gibes': 'NNS',
          'linden': 'NN', 'Maneret': 'NP-TL', 'baroness': 'NN', 'gingerly': 'RB', "catcher's": 'NN$', 'Perle': 'NP',
          'licking': 'VBG', 'consumed': 'VBD', 'Mandate': 'NN-TL', 'Lovejoy': 'NP', 'neatness': 'NN',
          'retrospective': 'NN', 'single-foot': 'VB', 'shape-up': 'JJ', 'disbelieves': 'VBZ', 'mariner': 'NN',
          'moontrack': 'NN', 'headlinese': 'NN', 'hubba': 'UH', 'easygoing': 'JJ', 'Elysees': 'NP', 'hoarseness': 'NN',
          'Strength': 'NN', 'solos': 'VBZ', 'Rests': 'VBZ', "Brush-off's": 'NP$', 'kazoo': 'NN', 'unease': 'NN',
          'inshore': 'RB', 'inspected': 'VBD', 'delighting': 'VBG', "Fudo's": 'NP$', 'Veneto': 'NP-TL',
          'Strippers': 'NNS', 'yaws': 'NNS', 'sprig': 'NN', 'rages': 'NNS', "Partlow's": 'NP$', 'crocked': 'VBN',
          'black': 'VB', 'fontanel': 'NN', 'Worms': 'NP-TL', 'ice-feeling': 'JJ', 'closeted': 'VBN',
          'Drive-in': 'NN-TL', 'Hostaria': 'NP', 'tonsil': 'NN', 'Musee': 'FW-NN-TL', 'Father': 'NN', 'deception': 'NN',
          'sophisticates': 'NNS', 'sit-down': 'NN', 'Wondering': 'VBG', 'belonging': 'NN', 'non-books': 'NNS',
          'slyly': 'RB', 'poling': 'VBG', 'bullhide': 'NN', 'mash': 'NN', 'Honshu': 'NP', 'Astonishingly': 'RB',
          "Salter's": 'NP$', 'villainous': 'JJ', 'Velasquez': 'NP', 'putains': 'FW-NNS', 'ranted': 'VBD',
          'multi-colored': 'JJ', 'prospering': 'VBG', 'prayerful': 'JJ', 'stumbles': 'VBZ', 'manure-scented': 'JJ',
          'spat': 'NN', 'distractions': 'NNS', 'straight-armed': 'VBD', '141': 'CD', 'convulsed': 'VBD',
          'cellophane': 'NN', 'hemlocks': 'NNS', 'Remy': 'NP', 'fancying': 'VBG', 'undying': 'JJ',
          'thousand-legged': 'JJ', "devil's-food": 'NN', 'Galway': 'NP', 'lonesome': 'JJ', 'scorcher': 'NN',
          'ocher': 'NN', 'Shivering': 'VBG', 'encyclopedia': 'NN', 'show-offy': 'JJ', 'uncolored': 'JJ',
          'shoelaces': 'NNS', 'Gresham': 'NP', 'babbiting': 'VBG', 'ginkgo': 'NN', 'V-shaped': 'JJ',
          'post-operative': 'JJ', 'pioneers': 'NNS', 'incubi': 'NNS', 'overhand': 'JJ', 'Shoals': 'NNS-TL',
          'brunettes': 'NNS', 'equivocal': 'JJ', 'bikinis': 'NNS', 'soirees': 'NNS', 'short-cut': 'JJ',
          'horoscope': 'NN', "Viola's": 'NP$', "'fess": 'VB', 'Javert': 'NP', "hall's": 'NN$', 'gagging': 'VBG',
          'eyeballs': 'NNS', 'Poitrine': 'NP', 'sibilant': 'JJ', 'jerk': 'VB', 'tint': 'NN', 'midshipmen': 'NNS',
          'proto-senility': 'NN', 'teething': 'VBG', 'speckled': 'VBN', 'glommed': 'VBD', 'adhesive': 'JJ',
          'curio': 'NN', 'hon': 'NN', 'Ferraro': 'NP', 'Goose': 'NN-TL', 'Presence': 'NN-TL', 'tart': 'NN',
          'Parioli': 'NP', 'stringed': 'VBN', 'Osric': 'NP', 'Doolittle': 'NP', 'ticking': 'VBG', 'jiffy': 'NN',
          'endearments': 'NNS', 'retrieve': 'VB', 'loincloth': 'NN', 'cocu': 'FW-NN', 'quench': 'VB',
          'Stuck-up': 'JJ-TL', 'Kohi': 'NP', 'decked': 'VBN', "Bradley's": 'NP$-TL', 'superseded': 'VBD',
          'Swift': 'NP-TL', 'slaughtering': 'VBG', 'coachwork': 'NN', 'black-and-yellow': 'JJ', 'Grazie': 'NP',
          'gourmet': 'NN', 'fig': 'NN', 'rings': 'VBZ', 'frenzied': 'JJ', 'availed': 'VBD', 'televison-record': 'NN',
          'lizards': 'NNS', 'Embarcadero': 'NP', 'pegboards': 'NNS', 'bouanahsha': 'FW-VB-NC', "company's": 'NN+HVZ',
          'Brush-off': 'NP', 'bathos': 'NN', 'Krishnaists': 'NPS', 'scalded': 'VBN', 'jaggedly': 'RB', 'outta': 'RP+IN',
          'Bobbie': 'NP', 'Appleby': 'NP', 'A40-AjK': 'NN', 'illustrators': 'NNS', 'screwed': 'VBD', 'Hurrays': 'NP',
          "Brace's": 'NP$', 'enamelled': 'VBN', 'chromed': 'VBN', "Beige's": 'NP$', 'mutineer': 'NN',
          "Someone's": 'PN+BEZ', 'delineaments': 'NNS', "one-o'clock": 'NN', 'Clouds': 'NNS-TL', 'Longfellow': 'NP',
          'fifty-third': 'OD', 'Edmonia': 'NP', 'Classified': 'VBN', 'CCC': 'NP-TL', 'lonelier': 'JJR',
          'luckier': 'JJR', 'Caligula': 'NP', 'Signor': 'NP', 'ramming': 'VBG', 'Doaty': 'NP', 'sun-warmed': 'JJ',
          'blood-soaked': 'JJ', 'black-balled': 'VBN', 'purple-black': 'JJ', 'Bowes': 'NP', 'demurred': 'VBD',
          'mares': 'NNS', "dryin'": 'VBG', 'blessing': 'VBG', 'vernacular': 'NN', 'grandsons': 'NNS', 'leftist': 'NN',
          'unbelievably': 'RB', 'Agnese': 'NP', 'quavering': 'VBG', 'boxed-in': 'JJ', 'drawn-back': 'JJ',
          'napping': 'VBG', 'all-pervading': 'JJ', 'well-bred': 'JJ', 'den': 'NN', 'sandpaper': 'NN',
          'slightly-smoking': 'JJ', 'omniscient': 'JJ', 'azalea': 'NN', 'rankles': 'VBZ', 'Welch': 'NP',
          'piously': 'RB', 'non-institutionalized': 'JJ', 'Cuba': 'NP-TL', 'pike': 'NN', 'Compassionately': 'RB',
          'bumps': 'NNS', 'kotowaza': 'FW-NN', 'Orly': 'NP', "Francesca's": 'NP$', 'Surviving': 'VBG-TL',
          'refracted': 'VBN', 'interns': 'NNS', 'jollying': 'VBG', 'brothel': 'NN', 'Sorry': 'JJ-NC', 'bathtubs': 'NNS',
          'what-nots': 'NNS', 'prowlers': 'NNS', 'Alma': 'NP', 'by-ways': 'NNS', 'two-burner': 'JJ', 'rime': 'NN',
          'insanely': 'RB', 'dollies': 'NNS', 'Faneuil': 'NP-TL', 'Wow': 'UH', 'snobs': 'NNS', 'Prometheus': 'NP',
          'non-repetitious': 'JJ', 'Rosalie': 'NP', 'paraphrasing': 'VBG', 'cooked-over': 'JJ', 'eye-beamings': 'NNS',
          'to-do': 'NN', "Hell's": 'NN$', 'comic': 'NN', 'tick': 'NN', 'sacking': 'VBG', 'bittersweet': 'JJ',
          'Straightened': 'VBN', 'drunk': 'VBD', 'concentrated': 'VBD', 'rippled': 'VBD', 'ex-jazz': 'NN',
          'Left': 'VBD', 'Fights': 'NNS', 'eating': 'NN', 'Alps': 'NPS-TL', 'Laban': 'NP', 'incongruity': 'NN',
          'Heavy': 'JJ', 'fine': 'VB', 'sun-tan': 'NN', 'une': 'FW-AT', 'refuse-littered': 'JJ', 'triplets': 'NNS',
          "Dave's": 'NP$', 'tune-belly': 'NN', 'paleness': 'NN', 'Abernathys': 'NPS', 'undulated': 'VBD',
          'raffish': 'JJ', 'tide': 'VB', 'merriest': 'JJT', 'Books': 'NNS-TL', 'oystchers': 'NNS', 'Oyajima': 'NP',
          'Multiple': 'JJ-HL', 'cabaret': 'NN', 'Rilke': 'NP', 'daydreamed': 'VBD', 'fortresses': 'NNS',
          'groaning': 'VBG', 'Coughlin': 'NP-TL', 'discolored': 'VBN', 'disbelieving': 'VBG', 'Toodle': 'NP',
          'dark-blue': 'JJ', 'overgenerous': 'JJ', 'Delia': 'NP', 'long-hair': 'NN', 'valued': 'VBD', 'pro-ball': 'NN',
          "musn't": 'MD*', 'Mesta': 'NP', 'antisocial': 'JJ', 'indoctrination': 'NN', 'homesteads': 'NNS',
          'pinch-hit': 'VB', 'shipshape': 'JJ', "whip's": 'NN$', 'extremis': 'FW-NNS', 'drunken': 'VBN',
          'implausibly': 'RB', 'rebound': 'NN', 'four-wheel-drive': 'NN', 'retaliate': 'VB', 'udon': 'FW-NN',
          'sour': 'JJ', 'stupefying': 'VBG', 'Homes': 'NNS', "Miranda's": 'NP$', 'drawing-rooms': 'NNS', 'waned': 'VBN',
          "'ello": 'UH', 'rakishly': 'RB', 'gleeful': 'JJ', 'boast': 'NN', 'leafed': 'VBD', 'Anglo-American': 'JJ',
          'mild-voiced': 'JJ', 'Metronome': 'NN-TL', 'leaps': 'VBZ', 'Futotsu': 'NP', 'kimono': 'NN', 'regalia': 'NNS',
          'horse-blanket': 'NN', 'flee': 'VB', 'hare': 'NN', 'hundred-yen': 'JJ', 'pinkish-white': 'JJ',
          'Websterville': 'NP', 'thickest': 'JJT', 'skeletons': 'NNS', 'Sylphide': 'NP', 'plaids': 'NNS',
          'Sforzt': 'NP', 'Hubba': 'UH', 'certain': 'FW-JJ', "Herberet's": 'NP$', 'ram': 'VB', 'Niobe': 'NP',
          'Mister': 'NP-TL', 'mailman': 'NN', 'shaking': 'NN', 'bangs': 'NNS', 'midsts': 'NNS', 'Astronomy': 'NN',
          'Via': 'FW-NN-TL', 'miuchi': 'FW-VB', 'Fortman': 'NP', 'theatregoer': 'NN', 'Fudomae': 'NP', 'unglued': 'JJ',
          'co-existence': 'NN', 'dark-gray': 'JJ', 'moors': 'NNS', "trippin'": 'VBG', 'Tuxapoka': 'NP',
          "goodness'": 'NN$', 'engages': 'FW-VBN', 'gossiping': 'VBG', 'five-seventeen': 'CD', 'spigots': 'NNS',
          'nudge': 'NN', 'Telling': 'VBG', 'eighteen-year-old': 'NN', 'bends': 'VBZ', 'gantlet': 'NN',
          'Lascivious': 'JJ-TL', 'bare-armed': 'JJ', 'fifty-fifty': 'JJ', 'gangway': 'NN', 'fetching': 'VBG',
          'blush': 'VB', 'shag': 'NN', "kind's": 'NN+BEZ', 'wild-eyed': 'JJ', 'panicky': 'JJ', "Hershey's": 'NP$',
          'cahoots': 'NNS', "Myra's": 'NP$', 'invocation': 'NN', 'silvas': 'FW-NNS', 'bellicosity': 'NN', 'Fudo': 'NP',
          'Bon': 'FW-JJ', 'Road': 'NN', 'polishing': 'VBG', 'Cappy': 'NP', 'bake': 'VB', 'Chateau': 'NP',
          'contentedly': 'RB', 'somersaulting': 'VBG', 'parapets': 'NNS', 'help': 'UH', 'ancient': 'NN',
          'scions': 'NNS', 'unrepentant': 'JJ', 'furrow': 'NN', 'Idol': 'NN-HL', 'tickled': 'VBD', 'Naval': 'JJ',
          'two-colored': 'JJ', 'idle': 'VB', 'clawing': 'VBG', "askin'": 'VBG', 'twirlingly': 'RB', 'Francie': 'NP',
          'cortege': 'NN', 'eyelid': 'NN', 'Pink': 'JJ', 'enrolling': 'VBG', 'nooks': 'NNS', 'mah-jongg': 'NN',
          'blondes': 'NNS', 'juju': 'NN', 'mem': 'FW-NN', "fielder's": 'NN$', 'carver': 'NN', 'prefectures': 'NNS',
          'stickman': 'NN', 'abstracted': 'VBD', "gran'dad": 'NP', 'forty-fifth': 'OD', 'launching': 'NN',
          "John'll": 'NP+MD', 'souffle': 'NN', 'ladle': 'NN', 'feasting': 'VBG', 'Mlle': 'NN', 'desert': 'NN-HL',
          'in': 'FW-IN', 'Chieti': 'NP', 'nondescriptly': 'RB', 'bachelor-type': 'JJ', 'Berche': 'NP', "Willis'": 'NP$',
          'Tooth-hurty': 'NN', 'spouting': 'VBG', 'Nodding': 'VBG', 'du': 'NP', 'Valentine': 'NP', 'Hear': 'VB',
          "Cappy's": 'NP$', "Maxim's": 'NP$', 'Rosie': 'NP', 'book-lined': 'JJ', 'handyman-carpenter': 'NN',
          'Arapacis': 'NP', 'fleet': 'JJ', 'astronaut': 'NN', 'Sameness': 'NN', 'Tuborg': 'NP',
          'Ubermenschen': 'FW-NNS', 'Lao-tse': 'NP', 'Mencius': 'NP', 'Thaxters': 'NPS', 'boarding-home': 'NN',
          'unhesitant': 'JJ', 'jinx': 'NN', 'eight-by-ten': 'CD', 'flog': 'VB', 'gorging': 'VBG', "Bartoli's": 'NP$',
          'Mousie': 'NP', 'Love': 'VB', 'Wrong': 'JJ', "caterer's": 'NN$', 'insomma': 'UH', 'scabrous': 'JJ',
          'delenda': 'FW-VBG', 'leprosy': 'NN', 'perpetration': 'NN', 'glissade': 'NN', 'Highfield': 'NP',
          'Alloy': 'NN', 'Hattie': 'NP', 'Titus': 'NP', 'Dolly': 'NP', 'migrated': 'VBN', 'Stake': 'VB', 'Mi': 'FW-PPO',
          'blackjack': 'NN', 'forebears': 'NNS', 'well-dressed': 'JJ', 'make-ready': 'NN', 'gypsies': 'NNS',
          'bone-deep': 'JJ', 'trestles': 'NNS', 'Pile': 'NN-TL', 'Carthago': 'FW-NP', 'Lalauries': 'NPS',
          'suppleness': 'NN', 'Feathertop': 'NP', 'politicking': 'NN', 'unsheathing': 'VBG', 'funnier': 'JJR',
          'subcontinent': 'NN', 'non-God': 'NP', "shores'": 'NNS$', 'zip': 'VB', 'ringlets': 'NNS', 'Resolving': 'VBG',
          'Carnegie-Illinois': 'NP', 'Mudugno': 'NP', 'plopped': 'VBD', 'blind': 'NN', 'scarify': 'VB', 'dawn': 'VB',
          'recapitulate': 'VB', 'Bake': 'JJ-TL', 'scattering': 'VBG', 'loudest': 'RBT', 'traipsing': 'VBG',
          'porridge': 'NN', 'soul-searching': 'JJ', "Quint's": 'NP$', 'Vue': 'NP', "Pockmanster's": 'NP$',
          'Edythe': 'NP', 'garnet': 'NN', "Ernie's": 'NP$', 'Engisch': 'NP', 'gray-looking': 'JJ', 'overhearing': 'VBG',
          'Bombay': 'NP', 'objets': 'FW-NNS', 'defined': 'VBD', 'shiver': 'NN', 'dusted': 'VBN', 'valiant': 'JJ',
          'Fredrico': 'NP', 'whitewashed': 'VBN', 'coverlet': 'NN', 'Miyagi': 'NP-TL', 'Dinsmore': 'NP',
          'tugging': 'VBG', 'splintered': 'VBN', 'Dillinger': 'NP', 'svelte': 'JJ', 'lammed': 'VBD', 'Comedy': 'NN',
          'rosebush': 'NN', 'Midshipman': 'NN-TL', "rain's": 'NN+HVZ', 'sacks': 'NNS', 'woolgather': 'VB',
          'binge': 'NN', 'Pyhrric': 'JJ', 'mops': 'NNS', 'over-large': 'JJ', 'horselike': 'JJ', 'soutane': 'NN',
          'fonder': 'JJR', "Welch's": 'NP$', 'mural': 'NN', 'frog': 'NN', 'tasteless': 'JJ', 'ogled': 'VBD',
          'tiredness': 'NN', 'rectitude': 'NN', 'frog-eating': 'JJ', 'eight-thirty': 'CD', 'slatted': 'JJ',
          'bright-eyed': 'JJ', 'sonny': 'NN', 'cutest': 'JJT', 'sting': 'VB', 'non-poetry': 'NN', 'Pull': 'VB',
          'Mobile': 'NN-TL', 'Lancaster': 'NP-TL', 'swiping': 'VBG', 'foals': 'NNS', 'gai': 'FW-JJ', 'hustler': 'NN',
          'flower-scented': 'JJ', 'helpmate': 'NN', 'swabbed': 'VBD', "Racin'": 'VBG-TL', 'nuzzled': 'VBD',
          'Angeles-Pasadena': 'NP-TL', 'Papanicolaou': 'NP', "gourmet's": 'NN$', 'Whittaker': 'NP', 'illustrator': 'NN',
          'Ahah': 'UH', 'tumbles': 'NNS', 'Orso': 'FW-NN-TL', 'Arcilla': 'NP', 'savor': 'NN', 'Bravado': 'NP',
          'toadies': 'NNS', 'Kandinsky': 'NP', 'indecipherable': 'JJ', 'vendor': 'NN', 'savagery': 'NN',
          "nobody'd": 'PN+HVD', 'non-dramas': 'NNS', 'Willis': 'NP', 'detained': 'VBD', 'wooden-leg': 'NN',
          'Cold': 'NN', 'Traitor': 'NN', 'Curly': 'JJ', 'bumming': 'NN', 'fluke': 'NN', 'sneezed': 'VBN',
          'Soaring': 'VBG', 'non-time': 'NN', 'unidentified': 'JJ', 'dang': 'JJ', 'child-cloud': 'NN',
          'chockfull': 'JJ', 'dens': 'NNS', 'rhinos': 'NNS', 'well-worn': 'JJ', 'Gratt': 'NP', 'mockingly': 'RB',
          'Marcellus': 'NP', 'Speedy': 'JJ-TL', 'scatterbrained': 'JJ', 'Prefecture': 'NN-TL', 'khaki': 'JJ',
          'pumpkin': 'NN', 'paot': 'FW-NN', 'Tradition': 'NN-TL', 'conning': 'VBG', 'Hun': 'NP', 'ere': 'CS',
          'clean': 'RB', 'probly': 'RB', 'LP': 'NP-TL', 'cartons': 'NNS', 'Thom': 'NP', 'goddamit': 'UH', 'Wynn': 'NP',
          'blister': 'VB', 'Canoe': 'NN-TL', 'scissoring': 'NN', 'parades': 'VBZ', 'Fleet': 'NN-TL',
          'living-room': 'NN', 'duds': 'NNS', 'footwear': 'NN', 'Barrymores': 'NPS', 'antic': 'JJ', 'ferreted': 'VBD',
          'wops': 'VBZ', "Tillie's": 'NP$', 'Ainu': 'NP', 'smear': 'NN', "Cathy's": 'NP$', 'Girls': 'NNS',
          'Washoe': 'NP-TL', 'harelips': 'NNS', 'Kali': 'NP', 'knightly': 'JJ', 'Carraway': 'NP', 'Snakes': 'NNS',
          'Belletch': 'NP', 'unadulterated': 'JJ', 'Britches': 'NNS-TL', 'dried-up': 'JJ', 'Lakes': 'NNS-TL',
          'Gord': 'NP-TL', 'misnomer': 'NN', 'daubed': 'VBD', 'Eph': 'NP', 'Bucks': 'NP-TL', 'Kezziah': 'NP',
          'geldings': 'NNS', 'dabbler': 'NN', 'greased': 'VBD', 'guinea': 'NN', 'long-sleeved': 'JJ',
          'Fascio-Communist': 'NP', 'dice': 'VB', 'imperilled': 'VBN', "dell'": 'FW-IN+AT-TL', 'underclothes': 'NNS',
          'Sort': 'NN', 'waitresses': 'NNS', 'paso': 'FW-NN', 'pruta': 'FW-NNS', 'lash': 'NN', 'lumbar': 'JJ',
          'lunatic': 'JJ', 'hubris': 'NN', 'is': 'BEZ-TL', "Jennie's": 'NP$', 'dozed': 'VBN', 'imperious': 'JJ',
          'freight-bums': 'NNS', "could've": 'MD+HV', "Brandon's": 'NP$', 'hard-come-by': 'JJ', 'hollowness': 'NN',
          'smokes': 'VBZ', "Grandma's": 'NN$-TL', 'dragooned': 'VBD', 'frenetic': 'JJ', 'Share': 'VB',
          'shrilled': 'VBD', 'metal-tasting': 'JJ', 'middle-Gaelic': 'NP', 'Siva': 'NP', 'unsee': 'VB', 'tomes': 'NNS',
          'sweatshirt': 'NN', 'yokel': 'NN', 'pettiness': 'NN', 'Farina': 'NP', 'soldierly': 'JJ', 'Michelson': 'NP',
          'translated': 'VBD', 'Quintus': 'FW-OD-NC', 'Madam': 'NN-TL', 'girl-friend': 'NN', 'Oooo': 'UH',
          'distrusted': 'VBN', 'Rawlings': 'NP', 'valueless': 'JJ', 'purgatory': 'NN', "Y'r": 'PP$', 'teakwood': 'NN',
          'zounds': 'UH', 'Magpie': 'NP-TL', 'whisperings': 'NNS', 'amulets': 'NNS', 'lacerate': 'VB', 'Haumd': 'NP',
          'Non-God': 'NP', 'Freddy': 'NP', 'Oakmont': 'NP', 'Lagoon': 'NP', 'warm-up': 'NN', 'old-grad-type': 'NN',
          "footballer's": 'NN$', 'Jean-Pierre': 'NP', 'rapping': 'NN', 'motorscooters': 'NNS', "Marquis'": 'NP$',
          "Susan's": 'NP$', 'Strangely': 'RB', 'effeminate': 'JJ', 'Galahad': 'NP', 'Heinzes': 'NPS',
          "cane's": 'NN+BEZ', 'larder': 'NN', 'graham': 'NN', 'statuette': 'NN', 'wondrous': 'JJ', 'open-handed': 'JJ',
          'Entwhistle': 'NP', 'clasped': 'VBD', 'Cursed': 'VBN', 'petted': 'VBN', 'rajah': 'NN', 'baffle': 'VB',
          'carte': 'NN', 'Fan': 'VB', 'dustbin': 'NN', 'taunting': 'VBG', 'attis': 'FW-NN', "Pietro's": 'NP+BEZ',
          'perfectionists': 'NNS', 'waggled': 'VBD', 'insulted': 'VBD', 'cavern': 'NN', 'grizzly': 'NN',
          'Czarship': 'NN-TL', 'peaches': 'NNS', 'pored': 'VBD', 'Three-day': 'JJ', 'Jour': 'FW-NN-TL',
          'chorused': 'VBD', 'Witter': 'NP', 'sub-assembly': 'NN', 'thinning': 'VBG', 'unfunnily': 'RB', "sor'l": 'JJ',
          'teas': 'NNS', 'sun-burned': 'JJ', 'Panther': 'NN-TL', 'rotten': 'JJ', 'miswritten': 'VBN',
          'yielding-Mediterranian-woman-': 'NN', 'crisscrossed': 'VBN', 'cheekbones': 'NNS', "Parkinson's": 'NP$',
          'fuss': 'NN', 'boxcars': 'NNS', 'chivying': 'VBG', 'balkiness': 'NN', 'Rattzhenfuut': 'NP', 'Eurasian': 'JJ',
          'indefinity': 'NN', 'Aw': 'UH', 'terrible': 'FW-JJ', 'Aliah': 'NP', 'primping': 'VBG', 'bested': 'VBN',
          'Eugenia': 'NP', 'Virus': 'NN', 'Ciao': 'FW-UH', 'Carrozza': 'FW-NN', 'Smithtown': 'NP', 'freights': 'NNS',
          "carpenter's": 'NN$', 'Addict': 'NN-HL', 'interweaving': 'VBG', 'Thrifty': 'JJ', 'Sheridan': 'NP',
          'raisin': 'NN', "d'Eiffel": 'FW-IN+NP-TL', 'sea-damp': 'NN', 'gumming': 'VBG', 'Kleenex': 'NP',
          'wallow': 'VB', 'Sarpsis': 'NP', "Anniston's": 'NP$', 'Philly': 'NP', 'slashes': 'NNS', "Y're": 'PPSS+BER',
          'joss': 'NN', 'yawn': 'NN', 'researches': 'NNS', 'dislocated': 'VBN', 'journalese': 'NN', 'Akita': 'NP',
          'Torah': 'NP', "Spumoni's": 'NP$', 'nonism': 'NN', 'woolly-minded': 'JJ', 'despoiling': 'VBG', 'Barco': 'NP',
          'Pickfair': 'NP', 'sleepwalker': 'NN', 'Robards': 'NP', 'anatomical': 'NN', 'sops': 'NNS', 'numerals': 'NNS',
          'wilt': 'NN', 'cowbirds': 'NNS', "Victoria's": 'NP$', 'to-and-fro': 'RB', 'Margo': 'NP', 'shame': 'VB',
          'areaways': 'NNS', 'jest': 'NN', 'Harro': 'UH', 'storm': 'VB', 'roast': 'VBN', 'connivance': 'NN',
          'hair-trigger': 'NN', 'Il': 'FW-AT-TL', 'pithy': 'JJ', 'Contact': 'NN', 'Buzz': 'NP', 'tamale': 'NN',
          'bicarbonate': 'NN', 'little-town': 'NN', "Eddie's": 'NP$', 'unsealed': 'VBN', 'Ranavan': 'NP-TL',
          'Sweating': 'VBG', 'Romances': 'NNS-HL', 'preceding': 'NN', 'unalloyed': 'JJ', 'Mio': 'FW-PP$-TL',
          'heatedly': 'RB', 'Salpetriere': 'NP', "Vivian's": 'NP$', 'Non': 'FW-RB', 'rushes': 'NNS', 'Blackwell': 'NP',
          'Umm': 'UH', 'yellowed': 'VBN', 'sprouted': 'VBD', 'instigation': 'NN', 'socio-archaeological': 'JJ',
          'Feeley': 'NP', 'usurious': 'JJ', 'pyre': 'NN', 'So-so': 'RB', 'Spagna': 'FW-NP-TL', 'six-thirty': 'CD',
          'gnomelike': 'JJ', 'birch': 'NN', 'fieldmice': 'NNS', 'second-story': 'NN', 'gaming': 'VBG', 'wet': 'VBN',
          'goooolick': 'UH', 'vicissitudes': 'NNS', 'country-squirehood': 'NN', 'loafed': 'VBD', 'Triomphe': 'FW-NN-TL',
          'tunneled': 'VBD', 'intraepithelial': 'JJ', "Tolley's": 'NP$', 'Bobbsey': 'NP-TL', 'ache': 'VB', 'sed': 'VBN',
          'pre-Punic': 'JJ', 'Nuf': 'AP', 'voiceless': 'JJ', 'dizziness': 'NN', 'pyramid': 'VB',
          'fifteenth-century': 'NN', 'girl-san': 'NN', 'scald': 'VB', 'lay-sisters': 'NNS', 'trilled': 'VBD',
          'Spegititgninino': 'NP-TL', 'broach': 'VB', 'oblige': 'NN', 'Prussian': 'JJ', 'coast-to-coast': 'NN',
          'chi-chi': 'NN', 'Donner': 'NP', 'shills': 'NNS', 'House': 'NN', "goat's": 'NN$', 'Cryptic': 'JJ',
          'ex-musician': 'NN', 'Moreland': 'NP', 'sidle': 'VB', 'unearthed': 'VBD', 'octoroon': 'NN', "Letch's": 'NP$',
          'Gwen': 'NP', 'orphanage': 'NN', 'crackling': 'NN', 'Sierras': 'NPS', 'Implements': 'NNS', 'stealer': 'NN',
          'vampires': 'NNS', 'inspirational': 'JJ', 'Carpenters': 'NNS', 'Ye': 'AT-TL', 'canvassing': 'NN',
          'dial': 'NN', 'Poldowski': 'NP', 'queried': 'VBD', 'sunburn': 'NN', 'tragicomic': 'JJ', 'plowshares': 'NNS',
          'palisades': 'NNS', 'Colosseum': 'NP', 'anesthetic': 'NN', "Idiot's": 'NN$', 'disquiet': 'NN',
          'gnarled': 'JJ', 'Tough': 'JJ', 'non-fiction': 'NN', 'incessantly': 'RB', 'heavers': 'NNS', 'pap': 'NN',
          'stormbound': 'JJ', 'Allons': 'FW-VB', 'scenario': 'NN', 'Champs': 'FW-NNS-TL', 'Necklace': 'NN-TL',
          'put-upon': 'JJ', 'Sponge': 'NN-TL', 'calculators': 'NNS', 'Jeroboam': 'NP', 'Stubblefield': 'NP',
          'screenland': 'NN', 'Sole': 'FW-NN-TL', 'hiccups': 'NNS', 'fainted': 'VBN', 'eatables': 'NNS',
          'Felicity': 'NP', 'whitehaired': 'JJ', "Poitrine's": 'NP$', 'Real': 'QL', 'double-entendre': 'NN',
          'Baccarat': 'NP', 'curvaceously': 'RB', 'pfffted': 'VBD', 'tapping': 'VBG', 'Lilliputian': 'JJ',
          'nonconformist': 'NN', 'limp': 'NN', 'pajama': 'NN', 'delimit': 'VB', 'Lie': 'VB', 'dogs': 'VBZ',
          'M.': 'NP-TL', 'Cantor': 'NP', 'Run-down': 'JJ', 'quibs': 'NNS', 'fingerings': 'NNS', 'Starkey': 'NP',
          'wheezes': 'NNS', 'zoooop': 'UH', 'salivate': 'VB', "soon's": 'RB+CS', 'Mehitabel': 'NP',
          'veterinarian': 'NN', 'amateurishness': 'NN', 'heroically': 'RB', 'sneezing': 'VBG', 'exquisitely': 'RB',
          'hopscotch': 'NN', 'vestments': 'NNS', 'workbench': 'NN', 'bibles': 'NNS', 'hangouts': 'NNS', 'heiress': 'NN',
          'Horror': 'NN-TL', "Whyn't": 'WRB+DOD*', 'Nadine': 'NP', 'combat': 'FW-NN', 'propositioned': 'VBN',
          'rose': 'JJ', 'shatters': 'VBZ', 'Deslonde': 'NP', 'mastiff': 'NN', 'Ah-ah': 'UH', "grabbin'": 'VBG',
          'Walitzee': 'NP', 'heavy-handed': 'JJ', 'Letch': 'NP', 'upbringing': 'NN', "Cromwell's": 'NP$',
          'donning': 'VBG', 'Ferraros': 'NPS', 'slapped': 'VBN', 'hundred-and-fifty': 'CD', 'Hardware': 'NN-TL',
          'Hardwicke': 'NP', 'Quinzaine': 'NP-TL', 'Regretfully': 'RB', 'Montmartre': 'NP', 'scared': 'VBD',
          'saner': 'JJR', 'hunts': 'NNS', 'Fatso': 'NP', 'trucker': 'NN', 'Airless': 'JJ', 'Deegan': 'NP',
          'armload': 'NN', 'debs': 'NNS', 'Gorboduc': 'NP', 'shill': 'NN', 'beat-up': 'JJ', 'self-serve': 'NN',
          'Kiz': 'NP', 'Angleterre': 'FW-NP', 'crossroading': 'VBG', 'alligator': 'NN', 'jet-black': 'NN',
          "lovers'": 'NNS$', 'Mont': 'NP', 'grindstone': 'NN', 'cheesecloth': 'NN', 'womanly': 'JJ', 'Signora': 'NP',
          'prickly': 'RB', 'biwa': 'FW-NN', 'double-meaning': 'NN', "Barco's": 'NP$', 'hemming': 'VBG', 'Gunny': 'NP',
          'lug': 'VB', 'glisten': 'NN', 'limpid': 'JJ', 'Farnese': 'NP-TL', 'navy-blue': 'JJ', 'Bustard': 'NP',
          'dampening': 'VBG', 'caressed': 'VBN', 'tube-nosed': 'JJ', "sayin'": 'VBG', 'wearied': 'VBD',
          'Ruffians': 'NNS', 'weather-royal': 'JJ', 'guzzled': 'VBD', 'hammer': 'VB', 'Scrooge-like': 'JJ',
          'caper': 'NN', 'Colmans': 'NPS', 'contralto': 'NN', 'Herberet': 'NP', 'intrepid': 'JJ', 'Rapping': 'VBG',
          'variegated': 'VBN', 'derriere': 'NN', 'misquoted': 'VBN', 'clanking': 'VBG', 'Viyella': 'NP',
          'jiggling': 'VBG', 'Shades': 'NNS-TL', 'farmed': 'VBD', 'It-wit': 'NN', 'buckling': 'VBG', 'Rhine-Main': 'NP',
          'Tschilwyk': 'NP', 'trump': 'VB', 'crestfallen': 'JJ', 'daddy': 'NN', 'clattering': 'VBG', 'teddy': 'NN',
          'nylon': 'NN', 'kid': 'VB', 'Worst': 'JJT', 'crumble': 'VB', 'blazer': 'NN', 'Dying': 'VBG-TL',
          'sallow': 'JJ', 'uhhu': 'UH', 'satirist': 'NN', "Me'a": 'NP', 'pulse': 'VB', 'talons': 'NNS', "A's": 'NP-TL',
          'Eskimos': 'NPS', "Riverside's": 'NP$', 'Gorshek': 'NP', 'mightily': 'RB', 'faim': 'FW-NN',
          'streetlight': 'NN', 'IQ': 'NP-TL', 'bucking-up': 'NN', 'unquenched': 'JJ', 'misrelated': 'VBN',
          'Height': 'NN', 'doble': 'FW-JJ', 'Uhhu': 'UH', "Jenny's": 'NP$', 'frog-haiku': 'NN',
          "Christians'": 'NPS$-TL', 'flat-footed': 'JJ', 'lower-cut': 'JJR', 'disheveled': 'VBN', 'badgering': 'VBG',
          'william': 'NN', 'pre-packed': 'JJ', 'showroom': 'NN', 'Bizarre': 'JJ', 'haunting': 'VBG', 'garlanded': 'VBD',
          'screaming': 'NN', "dam'": 'JJ', 'Pioneers': 'NNS-TL', 'no-good': 'JJ', 'misinterpreters': 'NNS',
          'contraptions': 'NNS', 'deprived': 'VBD', 'harshened': 'VBD', 'process-server': 'NN', 'Pagan': 'NN-TL',
          'Shuz': 'NP', 'leaned': 'VBN', "folks'": 'NNS$', 'strafe': 'FW-VB', 'Rhyme': 'VB', 'uh': 'UH',
          'hinting': 'VBG', 'TuHulHulZote': 'NP', 'fisted': 'VBD', 'jotting': 'VBG', "f'r": 'IN', 'leggings': 'NNS',
          'New-Waver': 'NP', 'Murkland': 'NP', "Wally's": 'NP+HVZ', 'Bar-H': 'NP', 'Toujours': 'FW-RB',
          'Blackwells': 'NPS', 're-explore': 'VB', 'darn': 'VB', 'misty-eyed': 'JJ', 'Komurasaki': 'NP',
          'John-and-Linda': 'NPS', 'non': 'JJ', 'peacocks': 'NNS', 'movie-goer': 'NN', "Blatz's": 'NP$',
          'Messiah': 'NP', 'invigorating': 'VBG', "this'll": 'DT+MD', 'titters': 'NNS', 'flowerpot': 'NN',
          "Paglieri's": 'NP$-TL', 'restively': 'RB', 'fur-piece': 'NN', 'sweathruna': 'FW-NN-NC', 'Nabisco': 'NP',
          'clucked': 'VBD', 'undressed': 'VBD', 'Louvre': 'NP', 'Neurenschatz': 'NP-TL', 'Arc': 'FW-NN-TL',
          "'most": 'RB', 'Eddies': 'NNS-TL', 'perk': 'VB', 'Handsomest': 'JJT', 'colloquy': 'NN', 'Province': 'NN-TL',
          'indefinite': 'NN', 'Correspondence': 'NN', 'rung': 'VBN', 'serenaded': 'VBD', 'fit': 'VBD',
          'sucker-rolling': 'JJ', 'Merry-go-round': 'NN-TL', 'Bogartian': 'JJ', "Mathias'": 'NP$', 'finely-spun': 'JJ',
          '407': 'CD', 'mollified': 'VBN', 'Southland': 'NP-TL', 'less-dramatic': 'JJ', 'provenance': 'NN',
          'Allstates': 'NPS', 'laughingly': 'RB', 'Gladdy': 'NP', 'upturned': 'JJ', 'will': 'VB', 'loon': 'NN',
          'Pils': 'NN-TL', 'hearse': 'NN', 'slaying': 'VBG', 'sewed': 'VBN', 'uncoiling': 'VBG', 'ladylike': 'JJ',
          'honeymooning': 'VBG', 'retrogressive': 'JJ', 'fairy-tale': 'NN', 'Shapes': 'NNS', 'aviary': 'NN',
          'competency': 'NN', 'Enrico': 'NP-TL', 'compound-engine': 'NN', 'minded': 'VBD', 'lubricated': 'VBN',
          'ascetic': 'NN', "Monmouth's": 'NP$', 'Bremerton': 'NP', 'crap': 'NN', "A-Z's": 'NP$', 'Whipsnade': 'NP',
          'Shabbat': 'NP', 'curing': 'VBG', 'oneasy': 'JJ', 'sweetpeas': 'NNS', 'Victrola': 'NP', 'Vivian': 'NP',
          'pegboard': 'NN', "Hamrick's": 'NP$', 'unamused': 'JJ', 'Sevigli': 'NP-TL', 'notoriety': 'NN',
          'bannnnnng': 'UH', 'tidiness': 'NN', 'goldsmith': 'NN', 'coffers': 'NNS', 'Stern-faced': 'JJ',
          'coincidental': 'JJ', 'messing': 'VBG', 'Jennie': 'NP', 'manic': 'JJ', 'chiding': 'VBG', 'sweeter': 'JJR',
          'Dolan': 'NP', 'Unusual': 'JJ', 'wrenches': 'NNS', 'defeatism': 'NN', 'Adrien': 'NP', 'marshmallows': 'NNS',
          'worktable': 'NN', 'housebreakers': 'NNS', 'yearned': 'VBN', 'underwear': 'NN', 'stable-garage': 'NN',
          'jade': 'NN', 'storming': 'VBG', 'Subic': 'NP', 'sappy': 'JJ', 'whimper': 'VB', 'yell': 'VB',
          'worshiped': 'VBN', 'dwelt': 'VBD', 'undoing': 'NN', 'parisology': 'NN', 'beggary': 'NN', 'scimitar': 'NN',
          'tramp': 'NN', 'wallowed': 'VBD', "Phil's": 'NP$', 'Flotilla': 'NP', 'Kline': 'NP', 'maltreat': 'VB',
          "lad's": 'NN$', 'tinkling': 'VBG', 'alleyways': 'NNS', 'red-blooded': 'JJ', 'arrowheads': 'NNS',
          "Emma's": 'NP$', 'frogs': 'NNS', 'Stubblefields': 'NPS', 'Bookies': 'NNS', 'snuffboxes': 'NNS',
          'malign': 'JJ', 'abstract': 'NN', 'Collector': 'NN-TL', 'Aging': 'VBG', 'bellyfull': 'NN', 'monies': 'NNS',
          'upshot': 'NN', 'Pack': 'VB', 'anyplace': 'RB', 'lucy': 'NN', 'ruefulness': 'NN', 'collation': 'NN',
          'digger': 'NN', 'undertaker': 'NN', 'View': 'NN', 'equal': 'NN', 'souvenirs': 'NNS', 'Hetty': 'NP',
          'hunched-up': 'JJ', "Cotter's": 'NP$', 'value': 'VB', 'low-priced': 'JJ', "Carla's": 'NP$',
          'curtain-raiser': 'NN', 'mailbox': 'NN', "oystchers'll": 'NNS+MD', "Haumd's": 'NP$', 'Tillotson': 'NP',
          'martingale': 'NN', "nurses'": 'NNS$', 'Iijima': 'NP', 'fireplaces': 'NNS', 'marbleized': 'VBN',
          'Schlek': 'NP', 'Gerry': 'NP', 'Cherokee': 'NP', 'blossomed': 'VBD', 'palest': 'JJT', 'boucle': 'NN',
          'loathing': 'VBG', "Doolittle's": 'NP$', 'obligated': 'VBD', 'Dookiyoon': 'NP', 'nice': 'RB',
          'beautifully-tapered': 'JJ', "Morris'": 'NP$', 'beatification': 'NN', 'unbeknownst': 'JJ', 'rapped': 'VBN',
          'Abernathy': 'NP', 'telegraph': 'VB', '$85,000': 'NNS', 'Sooner': 'RBR', 'thuds': 'NNS', 'glorying': 'VBG',
          'muddling': 'VBG', 'pinball': 'NN', 'Human': 'NN', 'Schmalma': 'NP', 'sours': 'VBZ', 'Thuggee': 'NP',
          'Doug': 'NP', 'co-star': 'NN', 'Ida': 'NP', 'Bronx': 'NP-TL', 'Capistrano': 'NP', 'flaxen': 'JJ',
          "Rossilini's": 'NP$', 'Meinckian': 'JJ', 'affianced': 'VBN', 'keno': 'NN', 'Ainus': 'NPS', 'sulks': 'NNS',
          'swanlike': 'JJ', 'magnum': 'NN', 'pugh': 'UH', 'paranoiac': 'NN', 'gaspingly': 'RB', 'playroom': 'NN',
          'complaisant': 'JJ', 'Pietro': 'NP', 'shooing': 'VBG', 'Chadroe': 'NP', "Pompeii's": 'NP$', 'Aquacutie': 'NP',
          'murdering': 'VBG', "Linda's": 'NP$', 'snick': 'NN', 'SS.': 'NP', 'availing': 'VBG',
          'Brest-Silevniov': 'NP-TL', 'adored': 'VBD', 'tongue-twister': 'NN', 'multicolored': 'JJ', 'bedstraw': 'NN',
          'bludgeon': 'VB', 'Ganessa': 'NP', 'gauze': 'NN', 'half-murmured': 'JJ', 'catchee': 'VB', 'Appaloosas': 'NPS',
          'mackerel': 'NN', 'Maurier': 'NP', 'Henh': 'UH', 'lemon-meringue': 'NN', 'Extending': 'VBG', 'hail': 'VB',
          'subsist': 'VB', 'Dazed': 'VBN', 'all-lesbian': 'JJ', 'Partlow': 'NP', 'topgallant': 'NN',
          'parent-teacher': 'NN', 'Diego': 'NP', 'squat': 'VB', 'unclasping': 'VBG', 'bagpipe': 'NN', 'mouthful': 'NN',
          'hit-and-miss': 'JJ', "clergyman's": 'NN$', "Blackwell's": 'NP+BEZ', "Doaty's": 'NP$', 'eyelashes': 'NNS',
          "Horne's": 'NP$', 'bedspread': 'NN', 'wetness': 'NN', 'pattered': 'VBD', 'pales': 'NNS', 'clobbered': 'VBD',
          'off-road': 'JJ', 'loosened': 'VBD', "murderer's": 'NN$', 'philharmonic': 'NN', 'pickles': 'NNS',
          'romping': 'VBG', 'laced': 'VBN', 'rousing': 'VBG', 'nervously': 'RB', 'convivial': 'JJ', 'dewdrops': 'NNS',
          'Puttana': 'FW-NN', 'polio': 'NN', 'Hanford': 'NP', 'Alternately': 'RB', 'Ticonderoga': 'NP',
          'ordnance': 'NN', 'felled': 'VBN', 'chided': 'VBD', 'Nineveh': 'NP', 'Forked': 'VBN-TL', 'chuck-a-luck': 'NN',
          'nnuolapertar-it-vuh-karti-birifw-': 'NN', 'chillier': 'JJR', 'Astronaut': 'NN-TL', 'after-duty': 'JJ',
          'Suzuki': 'NP', 'Diet': 'NN-TL', 'coral-colored': 'JJ', 'wop': 'VB', 'Soba': 'FW-NN', 'mama': 'NN',
          'Errol': 'NP', 'rock-carved': 'JJ', 'Cafritz': 'NP', "flautist's": 'NN$', 'patina': 'NN', 'Tanin': 'FW-NNS',
          'N': 'NP-TL', 'encouragingly': 'RB', 'abated': 'VBD', 'paraded': 'VBD', 'collective': 'NN', 'Fearless': 'JJ',
          'rooftree': 'NN', 'Zend-Avesta': 'NP', 'Anglo-Americans': 'NPS', 'ceremonially': 'RB', 'vandals': 'NNS',
          'jokers': 'NNS', 'WPA': 'NP-TL', "l's": 'NN', "what're": 'WDT+BER', 'Factory-to-You': 'NN-TL',
          'Hastening': 'VBG', 'sidesteps': 'VBZ', 'thimble': 'NN', 'cameo-like': 'JJ', 'telephoning': 'NN',
          "Fran's": 'NP$', 'Zeitgeist': 'FW-NN', 'caged': 'VBN', 'play-off': 'NN', 'earth-touching': 'JJ',
          'beholds': 'VBZ', 'sheds': 'NNS', 'husband-stealer': 'NN', 'five-days-a-week': 'JJ', 'Daughter': 'NN-TL',
          'portant': 'FW-VB', 'outsized': 'JJ', 'gabble': 'NN', 'tinkers': 'NNS', 'Pulova': 'NP', 'Agoeng': 'NP',
          'Grimesby': 'NP', "Baseball's": 'NN+BEZ', 'blanche': 'JJ', 'Capricorn': 'NP-TL', 'discarded': 'VBD',
          "Crombie's": 'NP$', 'grata': 'FW-JJ', 'understated': 'VBN', 'whine': 'NN', 'hysterectomy': 'NN',
          'assortment': 'NN', 'Doors': 'NNS', 'fire-colored': 'JJ', 'Pleasant': 'NP', 'big-boned': 'JJ',
          "Fair's": 'NN$-TL', 'two-by-fours': 'NNS', 'boy-name': 'NN', 'Prisoners': 'NNS', 'Weakness': 'NN',
          'creamed': 'VBN', 'movie-to-be': 'NN', 'dugout': 'NN', 'flatter': 'VB', 'pinging': 'VBG', 'Cause': 'NN',
          'armadillo': 'NN', 'parachute': 'NN', 'anti-personality': 'JJ', 'stubble': 'NN', "Charlotte's": 'NP$',
          'applejack': 'NN', 'next-door': 'JJ', 'Tillie': 'NP', 'gathers': 'VBZ', 'slackened': 'VBN', 'Mason': 'NP-TL',
          'bantered': 'VBN', 'Hmm': 'UH', 'Shops': 'NNS-TL', 'Downfall': 'NN-HL', 'bumped': 'VBD',
          'heart-stopping': 'JJ', 'rich': 'NN', 'exhaling': 'VBG', 'tool-kit': 'NN', 'Hamrick': 'NP', 'Grunnfeu': 'NP',
          'Dominique': 'NP', 'brig': 'NN', 'shackles': 'NNS', 'Tea': 'NN', 'ma': 'FW-CS', 'befell': 'VBD',
          'intimate': 'NN', 'tragically': 'RB', 'Reverently': 'RB', 'Captain': 'NN', 'browny-haired': 'JJ',
          'belligerence': 'NN', 'AA': 'NP-TL', "Maggie's": 'NP$', 'secured': 'VBD', 'ba-a-a': 'UH', 'log-house': 'NN',
          'Travancore': 'NP', 'thespians': 'NNS', 'gooshey': 'JJ', 'many-times': 'NNS', 'worrisome': 'JJ',
          'Thaxter': 'NP', 'Labans': 'NPS', 'shipwrecked': 'VBN', 'say': 'FW-VB', "Marshall's": 'NP$', 'starlet': 'NN',
          "t's": 'NN', 'Stopping': 'VBG', 'absurdly': 'RB', 'marinated': 'VBN', 'Mantegna': 'NP', 'symbolizing': 'VBG',
          "Hetty's": 'NP$', 'nearsighted': 'JJ', 'Rhinoceros': 'NN', 'Neitzbohr': 'NP', 'rhetoricians': 'NNS',
          'Mercedes': 'NP', 'paxam': 'FW-NN', 'surcease': 'NN', 'Heads': 'NNS', 'constables': 'NNS', 'hairpin': 'NN',
          'bumptious': 'JJ', 'Jobs': 'NNS', 'Theresa': 'NP', 'amazed': 'VBD', 'bandages': 'NNS', 'newly-plowed': 'JJ',
          'Kafka': 'NP', 'McCafferty': 'NP', 'O': 'FW-UH-TL', 'plunge': 'VB', 'bribe': 'VB', "Lucille's": 'NP+BEZ',
          'Prudence': 'NN-HL', 'Swan': 'NN-TL', 'yori': 'FW-NNS', 'dune': 'NN', 'Rossoff': 'NP', 'prohibitive': 'JJ',
          'good-by': 'NN', 'Khmer': 'NP', 'rollickingly': 'RB', 'lifelong': 'JJ', 'Upson': 'NP', 'je': 'FW-PPSS',
          'Angrily': 'RB', 'asparagus': 'NN', 'fielding': 'VBG', 'Expressionism': 'NN-TL', 'Squint': 'NP',
          'Invasion': 'NN-TL', 'horn-rimmed': 'JJ', 'swears': 'VBZ', 'mayorship': 'NN', 'Soothing': 'VBG',
          'etymological': 'JJ', 'curls': 'NNS', "strangers'": 'NNS$', 'Colts': 'NNS-TL', 'Italy': 'NP-TL',
          'hacksaw': 'NN', 'tinning': 'NN', 'Viola': 'NP', 'overvaulting': 'JJ', 'intruding': 'VBG', 'tweezed': 'VBN',
          'Eating': 'VBG', 'Ozon': 'NP', 'Crazy': 'JJ-TL', 'hilltops': 'NNS', 'brushlike': 'JJ', 'Nurse': 'NN-TL',
          'Ryusenji': 'NP', 'engagingly': 'RB', 'Portia': 'NP', 'spangle': 'NN', 'Stuart-family': 'JJ',
          'Bathar-on-Walli': 'NP-TL', 'counterbalance': 'NN', 'straight-A': 'JJ', 'social': 'NN', 'uttermost': 'NN',
          'Gansevoort': 'NP', 'Sirs': 'NNS', 'schoolgirls': 'NNS', "Robards'": 'NP$', 'Furnaces': 'NNS-TL',
          'misunderstanders': 'NNS', 'Tax': 'NN', 'coconut-containing': 'JJ', 'offal': 'NN', 'fancy-free': 'JJ',
          'Shawnee': 'NP', "Springfield's": 'NP+BEZ', 'crackles': 'VBZ', 'Couple': 'NN', 'whitened': 'VBD',
          'co-extinction': 'NN', 'frankest': 'JJT', 'Liliputian': 'JJ-TL', 'afghan': 'NN', 'pug-nosed': 'JJ',
          'fly-dotted': 'JJ', 'waspishly': 'RB', 'Somers': 'NP-TL', 'sparkled': 'VBD', "Koussevitzky's": 'NP$',
          'Sashimi': 'NN', 'Avocado': 'NN-TL', 'Mauve-colored': 'JJ', 'Esperanza': 'NP-TL', 'Weight': 'NN',
          'forepaws': 'NNS', 'prophesied': 'VBD', 'Mad': 'JJ', 'lapping': 'VBG', "Allstates'": 'NPS$', 'asunder': 'RB',
          'newly-scrubbed': 'JJ', 'Olde': 'JJ', 'fantods': 'NNS', 'lingerie': 'NN', 'fetes': 'NNS', 'Sabras': 'NPS',
          'solo': 'VB', 'Minks': 'NP', 'slights': 'NNS', 'plumbed': 'VBD', 'splashy': 'JJ', 'snapper': 'NN',
          'yodeling': 'VBG', 'matrimonial': 'JJ', 'Serbantian': 'JJ', "bee's": 'NN$', 'sizzle': 'VB', 'waltz': 'NN',
          'Hajime': 'NP', 'jour': 'FW-NN', 'grooved': 'VBN', 'Sir': 'NP-TL', 'hangers': 'NNS', "Dandy's": 'NP$',
          'polka-dotted': 'JJ', 'Sainted': 'JJ-TL', 'floodlit': 'VBN', 'crinkles': 'NNS', 'Constance': 'NP',
          'Anywhere': 'RB', 'ballplayers': 'NNS', 'Spike-haired': 'JJ', 'crimsoning': 'VBG', 'Hinkle': 'NP',
          'Larkspur': 'NN-TL', 'stubbed': 'VBN', 'thwump': 'NN', 'wardroom': 'NN', 'Interlude': 'NN-TL',
          'muffins': 'NNS', 'offbeat': 'JJ', 'disquietude': 'NN', 'Baby-dear': 'NP', 'boy-furiendo': 'NN',
          'Upstairs': 'RB', 'Hit': 'VB', 'seekingly': 'RB', 'freight-jumper': 'NN', 'Willows': 'NNS-TL',
          'dissipated': 'VBN', 'Haydon': 'NP', 'varicolored': 'JJ', 'dawns': 'VBZ', 'maxim': 'NN', 'garden': 'VB',
          'fermenting': 'VBG', 'Health': 'NN', 'cod': 'NN', 'tea-drinking': 'JJ', 'chaperon': 'NN', 'Art': 'BER',
          'unlaced': 'VBD', 'redheads': 'NNS', 'Ugh': 'UH', 'arboreal': 'JJ', 'Canute': 'NP', 'good-living': 'JJ',
          'gleefully': 'RB', 'Woods': 'NNS-TL', 'plaid': 'NN', 'bled': 'VBN', 'Adelia': 'NP', 'sickly-tolerant': 'JJ',
          'expunge': 'VB', "Flynn's": 'NP$', 'Epiphany': 'NN-TL', 'battle-ax': 'NN', 'Funk': 'NP-TL',
          'misconstructions': 'NNS', 'punch': 'VB', 'His': 'PP$-TL', "aunt's": 'NN$', 'fierceness': 'NN', 'Jerez': 'NP',
          'corrupts': 'VBZ', 'gasp': 'VB', 'floorshow': 'NN', 'Journalism': 'NN', "Nadine's": 'NP$', 'Sympathy': 'NN',
          'unventilated': 'JJ', 'double-married': 'JJ', 'checks': 'VBZ', 'snort': 'NN', 'bosoms': 'NNS',
          'Sour': 'JJ-TL', 'bookies': 'NNS', 'dooms': 'NNS', 'Kizzie': 'NP', "'ceptin'": 'IN', 'fretted': 'VBD',
          'Auto': 'NN-TL', 'Elec': 'NP', "ever'body": 'PN', 'walrus': 'NN', "leavin'": 'VBG', 'cameramen': 'NNS',
          'moon-washed': 'JJ', 'beseech': 'VB', 'bun': 'NN', 'tracings': 'NNS', 'Bits': 'NNS', 'gull': 'NN',
          "doctor's": 'NN+BEZ', "Gladdy's": 'NP$', 'noncommittally': 'RB', 'Tasti-Freeze': 'NP', 'salamander': 'NN',
          'Chase': 'NN-TL', 'small-car': 'NN', 'Sushi': 'FW-NN', 'noblesse': 'NN', 'sommelier': 'NN', 'deigned': 'VBD',
          'D.A.': 'NP', 'lifeguards': 'NNS', 'bolo': 'NN', 'well-organized': 'JJ', 'Beard': 'NN-TL',
          'Stimulating': 'JJ', 'incarcerated': 'VBN', 'orbit': 'VB', 'too-hearty': 'JJ', 'heartless': 'JJ',
          'pink': 'NN', 'jeans': 'NNS', 'Rummaging': 'VBG', 'makeshifts': 'NNS', 'overture': 'NN', 'bangish': 'JJ',
          "sun's": 'NN+BEZ', 'clinked': 'VBD', 'Reuveni': 'NP', 'saleslady': 'NN', "Hope's": 'NP$', 'whimpering': 'VBG',
          'imploring': 'VBG', 'browny': 'JJ', 'questioningly': 'RB', 'admiringly': 'RB', 'Alicia': 'NP',
          'aversion': 'NN', 'heavily-upholstered': 'JJ', 'Sometime': 'RB', 'ne': 'FW-*', 'moth': 'NN', 'snuck': 'VBD',
          'Acala': 'NP', "Pendleton's": 'NP$', 'Carrie': 'NP', 'icing': 'NN', 'rehearsing': 'VBG', 'hurt': 'VBD',
          'slat': 'NN', 'grasses': 'NNS', 'shouders': 'NNS', 'radish': 'NN', 'fountain-falls': 'NNS', 'invite': 'NN',
          'Yalagaloo': 'UH', 'stooooomp': 'VB', "jeweler's": 'NN$', 'Devout': 'JJ', "cowbirds'": 'NNS$', 'bag': 'VB',
          'Comics': 'NNS-TL', 'woulda': 'MD+HV', 'intoxicated': 'VBN', 'grand-daughter': 'NN', 'lulu': 'NN',
          'red-faced': 'JJ', 'Absolution': 'NN', 'off-key': 'JJ', 'hander': 'NN', 'encylopedia': 'NN', 'moonlit': 'JJ',
          'apparency': 'NN', 'Ethiopians': 'NPS', 'Bentley': 'NP', 'wolfishly': 'RB', 'handspikes': 'NNS',
          'thick-skulled': 'JJ', 'Heiser': 'NP', "Fleet's": 'NN$-TL', 'Brinsley': 'NP', 'amalgamation': 'NN',
          'semi-professionally': 'RB', 'hoi-polloi': 'FW-NNS', 'brutally': 'RB', "Basho's": 'NP$', 'non-nonsense': 'NN',
          'remoter': 'JJR', 'non-color': 'NN', 'Jehovah': 'NP', "batter's": 'NN$', 'ideologist': 'NN', 'Spector': 'NP',
          'overplayed': 'VBD', 'doped': 'VBN', "d'un": 'FW-IN+AT', 'pamper': 'VB', 'ham-radio': 'NN', 'Hostile': 'JJ',
          'Worry': 'NN', 'toilsome': 'JJ', 'thorns': 'NNS', 'hedge': 'NN', 'Mare': 'NN-TL', "Thom's": 'NP$',
          'princess-in-a-carriage': 'NN', 'Outsville': 'NP', 'six-month': 'JJ', 'Farneses': 'NPS', "ever'": 'AT',
          'Subdued': 'VBN', 'Guimet': 'NP-TL', 'bowing': 'VBG', 'unfunny': 'JJ', 'collapse': 'VB', 'Pueri': 'FW-NNS',
          'Budweisers': 'NPS', 'wisenheimer': 'NN', 'peppermints': 'NNS', 'Convention': 'NN', 'Concetta': 'NP',
          'cardinal': 'NN', 'half-smile': 'NN', 'Ishii': 'NP', 'rain': 'VB', 'quok': 'FW-WDT', 'unyielding': 'JJ',
          'topcoat': 'NN', 'pooh-poohed': 'VBD', 'glee': 'NN', 'non-readers': 'NNS', 'medium-sized': 'JJ', 'hop': 'NN',
          'Mmm': 'UH', 'Aquinas': 'NP', 'Showers': 'NP', 'laments': 'NNS', 'humiliated': 'VBN', 'over-pretended': 'JJ',
          'Ricco': 'NP', 'punks': 'NNS', 'Kool-Aid': 'NP', 'Elemental': 'JJ', 'tooth-paste': 'NN', 'cough': 'NN',
          'slumbered': 'VBD', 'commoners': 'NNS', 'timidly': 'RB', "Pete's": 'NP$', 'Guns': 'NNS-TL', 'alibis': 'NNS',
          'vibrating': 'VBG', 'squelched': 'VBN', 'instigator': 'NN', 'spa': 'NN', 'vitamin-and-iron': 'NN',
          'alcoholism': 'NN', 'Frail': 'JJ', 'scrubbing': 'NN', "Freddy's": 'NP$', 'Quizzical': 'JJ-TL', 'squirt': 'NN',
          'Occidental': 'JJ-TL', 'muster': 'NN', 'Infinite': 'JJ', 'cracks': 'VBZ', 'honeymooned': 'VBN',
          "Cargill's": 'NP$', 'unfrosted': 'JJ', 'estranged': 'VBD', 'pip': 'UH', 'age': 'FW-NN', "Kissin'": 'NN-TL',
          "Summer's": 'NN+HVZ', 'panties': 'NNS', 'Feebly': 'RB', 'heisted': 'VBD', 'closets': 'NNS', 'vise': 'NN',
          'curettage': 'NN', 'Caucasian': 'JJ', 'schooldays': 'NNS', 'over-spent': 'VBN', 'yapping': 'VBG', 'Son': 'NN',
          'Allah': 'NP', 'Filmdom': 'NN-TL', 'adult': 'JJ', 'elder': 'NN', 'drib-drool': 'NN', 'obsidian': 'NN',
          'Carthage': 'NP', 'bilharziasis': 'NN', 'Truckee': 'NP-TL', 'Jinny': 'NP', 'team-mate': 'NN',
          'ungallant': 'JJ', 'it': 'UH', 'Howdy': 'UH', 'leavings': 'NNS', 'liniment': 'NN', 'ultra-modern': 'JJ',
          'quarts': 'NNS', 'unpretentious': 'JJ', 'drudgery': 'NN', 'encircled': 'VBN', 'Evenings': 'NNS',
          'Encouraged': 'VBN', 'iron-poor': 'JJ', 'rifling': 'NN', 'somewheres': 'RB', 'Sabella': 'NP',
          "Deegan's": 'NP$', 'Conneaut': 'NP', 'tracked': 'VBN', 'jocose': 'JJ', 'commonest': 'JJT',
          'prayerbooks': 'NNS', 'unbent': 'VBN', 'Scotch': 'NP', 'Harvie': 'NP', 'self-served': 'VBD',
          'whiskered': 'JJ', 'hazel': 'NN', 'assorted': 'VBN', 'Bodhisattva': 'NP', 'gainer': 'NN', "C'mon": 'VB+RP',
          'Dunne': 'NP', 'inherits': 'VBZ', 'Zenith': 'NN-TL', 'sheeted': 'VBN', 'pinto': 'NN', 'Sparky': 'NP',
          'Yokosuka': 'NP', 'Aaawww': 'UH', 'Rufus': 'NP', "guy's": 'NN$', 'gardeners': 'NNS', 'Relatives': 'NNS',
          'Guggenheim': 'NP', 'Charcoal': 'NN', 'harshness': 'NN', 'situ': 'FW-NN', 'Astaires': 'NPS',
          'non-publishers': 'NNS', 'footstool': 'NN', 'Wrangler': 'NN-TL', 'Gott': 'FW-NP', 'Appian': 'NP-TL',
          'les': 'FW-AT', 'Baslot': 'NP', 'feelers': 'NNS', 'Daphne': 'NP', 'bout-de-souffle': 'FW-NN', 'Danger': 'NN',
          'Pugh': 'UH', 'whirling': 'NN', 'Parvenu': 'NP', 'unnnt': 'UH', 'Convulsively': 'RB', 'Nuit': 'FW-NN-TL',
          'alma': 'JJ', 'Puzzled': 'VBN', 'stumped': 'VBN', 'shoestring': 'NN', 'sundials': 'NNS', 'jade-handled': 'JJ',
          'furrowed': 'VBD', 'Traits': 'NNS-TL', 'Richert': 'NP', 'frambesia': 'NN', 'Blatz': 'NP', 'Grinned': 'VBN',
          'mask': 'VB', 'frilly': 'JJ', 'turtle-neck': 'NN', 'too-shiny': 'JJ', 'Tripoli': 'NP', 'Filling': 'VBG-TL',
          'forever-Cathy': 'NP', "Burnside's": 'NP$', 'diddle': 'UH', 'matter-of-factness': 'NN', 'teats': 'NNS',
          'jag': 'NN', 'bran': 'NN', 'puzzling': 'VBG', 'envenomed': 'VBN', 'fuchsia': 'NN', 'vanishes': 'VBZ',
          'exhaustingly': 'RB', 'unwaivering': 'JJ', 'white-columned': 'JJ'}

if __name__ == '__main__':
    train, test = ex2Sol.getTaggedSentences()
    # retNormal = ex2Sol.HMMbigramTagger(train_sentences=train,test_sentences=test)
    # print("loss - normal :{Normal}".format(Normal=retNormal))
    # retSmooth = ex2Sol.HMMbigramTaggerWithSmooth(train_sentences=train,test_sentences=test)
    # print("loss - Smooth :{Smooth}".format(Smooth = retSmooth))
    ret_pseudo = ex2Sol.HMMbigramTaggerWithPseudo(train,test,pseudo)
    print("loss - pseudo :{pseudo}".format(pseudo = ret_pseudo))
